###Constants

C_VERSION = "1.0.0"
C_FY = ("1920", "2021")
C_TAXFILE = 'taxrates.json'
C_INCREMENT_HOURLY = "Hourly"
C_INCREMENT_DAILY = "Daily"
C_INCREMENT_WEEKLY = "Weekly"
C_INCREMENT_FORTNIGHTLY = "Fortnightly"
C_INCREMENT_MONTHLY = "Monthly"
C_INCREMENT_ANNUALLY = "Annually"
C_WEEKSPYEAR = 50
C_MEDICARE_LEVY_RATE = 0.02

###